name: EnsoBench CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install Foundry (Anvil)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Build
        run: cargo build --workspace
      - name: Smoke run core route
        env:
          ENSO_API_KEY: ${{ secrets.ENSO_API_KEY }}
        run: cargo run -p ensobench-runner -- core-route --scenario dataset/coverage/r1_usdc_weth_route.yaml --simulate
      - name: Evaluate artifacts
        run: |
          LAST_RUN=$(ls -1d runs/*core-route | tail -n 1)
          cargo run -p ensobench-evaluator -- --per-tx "$LAST_RUN/per_tx.jsonl" --domains dataset/domains.enso.yaml
